### ISSUE TITLE
Investigate border or fuzzing edge

### ISSUE THREAD

**Issue by brendan-ward** [consbio/Leaflet.UTFGrid#1]
Glower had the ability to fake a border by using redrawing to the canvas with offsets.

We should be able to do that here.  Perhaps we can use that to smooth the edges, as well as creating just a border with no fill (by erasing the fill).

**Comment by gusmacaulay** [comment]
@brendan-ward - I would be interested in working on this and other styling options (eg. opacity), do you have any thoughts on what needs to be implemented?

**Comment by brendan-ward** [comment]
@gusmacaulay You can set opacity at the layer level now, using `.setOpacity()`.  You can also set opacity as part of the color, in the properties:

`fillColor: 'rgba(1, 100, 10, 0.7)'`

I think this is where I got the idea: https://github.com/cutting-room-floor/glower/blob/mb-pages/src/glower.js#L108

I think it is a matter of drawing on the canvas multiple times, with offsets.

What style options do you want? I'm thinking we might want:
- strokeWidth
- strokeColor

**Comment by gusmacaulay** [comment]
@brendan-ward  thanks, .setOpacity works as you say.

I've added the edge fuzzing from glower into my fork -  https://github.com/gusmacaulay/Leaflet.UTFGrid/network - I've also added a shadow styling option which sets the canvas shadowBlur option which I think combines nicely with the offset fuzzing technique.

I had a look at stroke styling but it's a little complicated because our image is made of many rectangles so setting stroke styling for the rectangles doesn't produce what we want.  I think maybe something like this is required - http://stackoverflow.com/questions/28207232/draw-border-around-nontransparent-part-of-image-on-canvas?rq=1
