### ISSUE TITLE
wms-wmts url

### ISSUE THREAD

**Issue by elanioazul** [consbio/Leaflet.UTFGrid#8]
Hi, 

I am struggling building my url to pass to L.utfGrid.

In the GetCapabilities of my wmts service I see:
http://domain/geoserver/gwc/service/wmts/rest/registrourbano:rt_tramofc_linea/{style}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}?format=application/json;type=utfgrid
I also see two TileMatrixSet, each with their own TileMatrixSetLimits.

I have tried as url:
0. http://domain/geoserver/gwc/service/wmts/1.0.0/registrourbano:rt_tramofc_linea@EPSG%3A900913/{z}/{x}/{y}?format=application/json;type=utfgrid

1. http://domain/geoserver/gwc/service/wmts/rest/registrourbano%3Art_tramofc_linea@EPSG%3A900913/{z}/{x}/{y}?format=application/json;type=utfgrid

2. http://domain/geoserver/gwc/service/wmts/?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=registrourbano:rt_tramofc_linea&TILEMATRIXSET=EPSG:900913&TILEMATRIX=EPSG:900913:{z}&TILEROW={y}&TILECOL={x}&FORMAT=application/json;type=utfgrid

But not success.

I am wondering if you have any example you can add to the README or index.html of this repository when requesting utfgrid against a geoserver service.
Also any help would be appreciate.

Thx

**Comment by elanioazul** [comment]
Giving me same error:
TypeError: this.callInitHooks is not a function
    at Object.NewClass [as UTFGrid] (leaflet-src.js:299)
    at eval (app_utfgrid.ts:29)
, pointing towards the url that I pass to L.utfGrid

**Comment by brendan-ward** [comment]
@elanioazul I don't use GeoServer or any WMTS servers, so I can't help you here.  Your URLs don't point to a valid server that I can test.

It might be worth looking at a [PR to add UTFGrids to OpenLayers](https://github.com/openlayers/ol2/pull/1486/files) using a WMS / WMTS source.  It looks like the URL used there is:
[http://demo.geo-solutions.it/geoserver/gwc/service/wmts/?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=topp:states&STYLE=_null&TILEMATRIXSET=EPSG:900913&TILEMATRIX=EPSG:900913:${z}&TILEROW=${y}&TILECOL=${x}&FORMAT=application/json;type=utfgrid](http://demo.geo-solutions.it/geoserver/gwc/service/wmts/?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=topp:states&STYLE=_null&TILEMATRIXSET=EPSG:900913&TILEMATRIX=EPSG:900913:${z}&TILEROW=${y}&TILECOL=${x}&FORMAT=application/json;type=utfgrid)

Which looks similar to your last URL, but includes a style statement and possibly other changes (note that `${x}` is not valid but `{x}` should be, for each parameter).

I suggest making a request (in your browser, using `cURL`, etc) to your UTFGrid endpoint and see what message you get.  There may be an XML response with an error message that would help you troubleshoot this (e.g., unsupported layer, etc).  Also make a test request against a tile that should exist by filling out the `z`,`x`,`y` parameters in the URL, and verify that you get back a UTFGrid.

For example, when I make a request to [http://demo.geo-solutions.it/geoserver/gwc/service/wmts/?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=topp:states&STYLE=_null&TILEMATRIXSET=EPSG:900913&TILEMATRIX=EPSG:900913:0&TILEROW=0&TILECOL=0&FORMAT=application/json;type=utfgrid](http://demo.geo-solutions.it/geoserver/gwc/service/wmts/?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=topp:states&STYLE=_null&TILEMATRIXSET=EPSG:900913&TILEMATRIX=EPSG:900913:0&TILEROW=0&TILECOL=0&FORMAT=application/json;type=utfgrid) with a specific `z`,`x`,`y`, I get back an error message about the layer.

If you are able to get this working, please feel free to submit a pull request to add an example for GeoServer / WMTS to the README.  Since this is not an error in Leaflet.UTFGrid, I'm going to close this issue.  If you find an underlying bug, please feel free to open an issue for that.
